name: Waka

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  GenerateWaka:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: False
          SHOW_PROJECTS: False
          SHOW_OS: False
          SHOW_LOC_CHART: False
          SHOW_TOTAL_CODE_TIME: False
