name: Snake

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  GenerateSnake:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            resources/github-contribution-grid-snake-light.svg
            resources/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push Snake
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: ":snake: Snake is eating github contributions..."
